client_id = "dev-key"
name = "AlertProof"
application_url = "http://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled", "app_subscriptions/update", "inventory_levels/update", "orders/create", "orders/paid", "order_transactions/create", "refunds/create"]
uri = "/webhooks/shopify"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks/shopify"

[access_scopes]
scopes = "read_orders,write_orders,read_products,read_inventory"

[auth]
redirect_urls = ["http://localhost:3000/auth/callback"]
