import { useLoaderData } from "react-router";
import { PublicPage, Section, styles } from "../components/PublicPage";
import { PLAN_FEATURES } from "../lib/billing/plans.server";
import { env } from "../lib/env.server";

export function meta() {
  return [
    { title: "Privacy policy — AlertProof" },
    {
      name: "description",
      content:
        "What data AlertProof collects from a Shopify store, why, how long it is kept, and how to request access or deletion.",
    },
  ];
}

export function loader() {
  return {
    supportEmail: env.SUPPORT_EMAIL,
    retention: {
      free: PLAN_FEATURES.FREE.retentionDays,
      standard: PLAN_FEATURES.STANDARD.retentionDays,
    },
  };
}

export default function Privacy() {
  const { supportEmail, retention } = useLoaderData<typeof loader>();

  return (
    <PublicPage
      title="Privacy policy"
      updated="13 August 2026"
      intro="AlertProof is a Shopify app that sends staff notifications about store events and records whether those notifications were delivered. This page describes exactly what it stores, why, and for how long."
    >
      <Section heading="Who this covers">
        <p>
          AlertProof processes data on behalf of the merchant who installs it.
          The merchant is the controller of their store&apos;s data; AlertProof
          is the processor. AlertProof does not sell data, does not use it for
          advertising, and does not use it to train machine-learning models.
        </p>
      </Section>

      <Section heading="What is collected">
        <table style={styles.table}>
          <thead>
            <tr>
              <th style={styles.th}>Data</th>
              <th style={styles.th}>Source</th>
              <th style={styles.th}>Why</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={styles.td}>
                Store domain, plan, timezone, install date, app settings
              </td>
              <td style={styles.td}>Shopify OAuth &amp; the app UI</td>
              <td style={styles.td}>
                Identify the store, apply plan entitlements, render times in the
                store&apos;s local timezone
              </td>
            </tr>
            <tr>
              <td style={styles.td}>
                Shopify API access token and the session record for the staff
                user who installed or opened the app (name, email, locale)
              </td>
              <td style={styles.td}>Shopify OAuth</td>
              <td style={styles.td}>
                Authenticate calls to the Shopify Admin API on the store&apos;s
                behalf
              </td>
            </tr>
            <tr>
              <td style={styles.td}>
                Order events and their payloads: order id and name, order value,
                financial status, refunds, transactions, inventory levels
              </td>
              <td style={styles.td}>Shopify webhooks and the Admin API</td>
              <td style={styles.td}>
                Evaluate alert rules, deduplicate events, and reconcile webhooks
                Shopify did not deliver
              </td>
            </tr>
            <tr>
              <td style={styles.td}>
                Recipient details the merchant enters: name, email address,
                phone number, Slack and Discord webhook URLs
              </td>
              <td style={styles.td}>Entered by the merchant in the app</td>
              <td style={styles.td}>Deliver alerts to the intended people</td>
            </tr>
            <tr>
              <td style={styles.td}>
                Delivery records: channel, destination, status, provider message
                id, timestamps, and provider error detail
              </td>
              <td style={styles.td}>
                Generated by AlertProof and by delivery-provider callbacks
              </td>
              <td style={styles.td}>
                Provide the delivery log — the proof that an alert arrived,
                bounced, or failed
              </td>
            </tr>
          </tbody>
        </table>
        <p>
          AlertProof does <strong>not</strong> request or store customer names,
          customer email addresses, shipping addresses, or payment details. It
          requests only the <code>read_orders</code>, <code>write_orders</code>,{" "}
          <code>read_products</code>, and <code>read_inventory</code> scopes.
        </p>
      </Section>

      <Section heading="Where it goes">
        <p>
          To deliver an alert, the message content and the recipient&apos;s
          destination address are sent to the delivery provider for that
          channel:
        </p>
        <ul style={styles.list}>
          <li>
            <strong>Email</strong> — Postmark (Wildbit, LLC), which also returns
            the delivery and bounce events that populate the delivery log.
          </li>
          <li>
            <strong>Slack / Discord</strong> — posted to the incoming-webhook
            URL the merchant configured.
          </li>
          <li>
            <strong>SMS</strong> — Twilio, only if the merchant supplies their
            own Twilio credentials.
          </li>
        </ul>
        <p>
          Delivery status is also written back to the originating Shopify order,
          so it stays with the order record. No other third party receives store
          data.
        </p>
      </Section>

      <Section heading="How it is protected">
        <ul style={styles.list}>
          <li>
            All traffic is served over HTTPS; the app runs only inside the
            Shopify admin frame after session-token authentication.
          </li>
          <li>
            Every incoming Shopify webhook is HMAC-verified and rejected if the
            signature does not match.
          </li>
          <li>
            Secrets a merchant supplies — Slack and Discord webhook URLs, and
            bring-your-own Twilio credentials — are encrypted at rest with
            AES-256-GCM under a key held outside the database.
          </li>
          <li>
            Data is partitioned per store; a query for one store can never
            return another store&apos;s records.
          </li>
        </ul>
      </Section>

      <Section heading="How long it is kept">
        <ul style={styles.list}>
          <li>
            Alert and delivery history follows the plan&apos;s retention window:{" "}
            {retention.free} days on Free, {retention.standard} days on
            Standard, unlimited on Pro. Records past the window are deleted.
          </li>
          <li>
            Raw webhook payloads are discarded after 30 days regardless of plan;
            only the derived alert record remains.
          </li>
          <li>
            Failed events kept for retry diagnosis are removed after 90 days.
          </li>
          <li>
            On uninstall, the app&apos;s access token and sessions are deleted
            immediately. Remaining store data is deleted when Shopify sends the{" "}
            <code>shop/redact</code> request, which Shopify issues 48 hours
            after uninstall.
          </li>
        </ul>
      </Section>

      <Section heading="Your rights">
        <p>
          AlertProof implements all three of Shopify&apos;s mandatory privacy
          webhooks — <code>customers/data_request</code>,{" "}
          <code>customers/redact</code>, and <code>shop/redact</code> — and acts
          on each substantively rather than acknowledging and discarding it.
        </p>
        <p>
          A merchant or an individual whose data appears in the app may request
          access, correction, export, or deletion at any time by emailing{" "}
          <a href={`mailto:${supportEmail}`}>{supportEmail}</a>. Requests are
          answered within 30 days. Recipients can also be deleted directly in
          the app, which removes their contact details and delivery history.
        </p>
      </Section>

      <Section heading="Changes">
        <p>
          Material changes to this policy will be reflected in the &ldquo;last
          updated&rdquo; date above, and merchants will be notified in-app
          before a change takes effect.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          <a href={`mailto:${supportEmail}`}>{supportEmail}</a>
        </p>
      </Section>
    </PublicPage>
  );
}
